spring.application.name=appointment
spring.datasource.url=jdbc:mysql://localhost:3306/clinicdb
spring.datasource.username=root
spring.datasource.password=GautamD@5678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secretKey = +tXkFdI5MNnWG9l6AgwaXofqdg1pIBw4n32/Owi8QoQ=
jwt.expiration-ms=86400000

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=javasystem05@gmail.com
spring.mail.password=cjsodeuaidtspcjy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.debug=true

logging.level.org.springframework.mail=DEBUG